// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Entities
{
    [Table("Inventory", Schema = "MAIN")]
    public partial class Inventory
    {
        [Key]
        public long Id { get; set; }
        public long ProductId { get; set; }
        public int? Quantity { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("Inventory")]
        public virtual Product Product { get; set; }
    }
}