// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Entities
{
    [Table("Product", Schema = "MAIN")]
    public partial class Product
    {
        public Product()
        {
            Inventory = new HashSet<Inventory>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(1000)]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        public int? Rating { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        public long ProductTypeId { get; set; }
        public long? BikeTypeId { get; set; }
        public long BrandId { get; set; }
        public long? ImageId { get; set; }

        [ForeignKey(nameof(BikeTypeId))]
        [InverseProperty("Product")]
        public virtual BikeType BikeType { get; set; }
        [ForeignKey(nameof(BrandId))]
        [InverseProperty("Product")]
        public virtual Brand Brand { get; set; }
        [ForeignKey(nameof(ImageId))]
        [InverseProperty(nameof(ProductImage.Product))]
        public virtual ProductImage Image { get; set; }
        [ForeignKey(nameof(ProductTypeId))]
        [InverseProperty("Product")]
        public virtual ProductType ProductType { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<Inventory> Inventory { get; set; }
    }
}