USE [master]
GO

/****** Object:  Database [BRU]    Script Date: 2/13/2023 3:53:52 PM ******/
CREATE DATABASE [BRU]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BRU', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BRU.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BRU_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BRU_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BRU] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BRU].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BRU] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BRU] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BRU] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BRU] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BRU] SET ARITHABORT OFF 
GO

ALTER DATABASE [BRU] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BRU] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BRU] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BRU] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BRU] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BRU] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BRU] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BRU] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BRU] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BRU] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BRU] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BRU] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BRU] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BRU] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BRU] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BRU] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BRU] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BRU] SET RECOVERY FULL 
GO

ALTER DATABASE [BRU] SET  MULTI_USER 
GO

ALTER DATABASE [BRU] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BRU] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BRU] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BRU] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BRU] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BRU] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BRU] SET  READ_WRITE 
GO


/****** Object:  User [apiuser]    Script Date: 2/13/2023 3:55:10 PM ******/
CREATE USER [apiuser] FOR LOGIN [apiuser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [apiuser]
GO
